# Generated by Django 5.0.4 on 2025-10-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20251020_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
