# Generated by Django 5.0.4 on 2025-10-22 09:46

from django.db import migrations

def set_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')

    for p in PersonModel.objects.all():
        if p.age < 13:
            p.age_group = "Child"
        elif p.age < 18:
            p.age_group = "Teen"
        else:
            p.age_group = "Adult"
        p.save()

def reverse_set_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    for p in PersonModel.objects.all():
        p.age_group = 'No age group'
        p.save()




class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_person'),
    ]

    operations = [
        migrations.RunPython(
            code=set_age_group,
            reverse_code=reverse_set_age_group
        )
    ]

