# Generated by Django 5.0.4 on 2025-10-22 10:52

from django.db import migrations

def set_rarity(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")
    for i in ItemModel.objects.all():
        if i.price < 11:
            i.rarity = "Rare"
        elif i.price < 21:
            i.rarity = "Very Rare"
        elif i.price < 31:
            i.rarity = "Extremely Rare"
        else:
            "Mega Rare"
        i.save()

def reverse_set_rarity(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")
    default_rarity = ItemModel._meta.get_field('rarity').default
    for i in ItemModel.objects.all():
        i.rarity = default_rarity

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(code=set_rarity, reverse_code=reverse_set_rarity)
    ]
