# Generated by Django 5.0.4 on 2025-10-22 12:04

from django.db import migrations

from main_app.models import Smartphone


def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    for phone in SmartphoneModel.objects.all():
        phone.price = len(phone.brand) * 120
        phone.save()

def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    for phone in SmartphoneModel.objects.all():
        if phone.price >= 750:
            phone.category = "Expensive"
        else:
            phone.category = "Cheap"
        phone.save()

def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)

def reverse_set_price_and_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_category = SmartphoneModel._meta.get_field('category').default

    for phone in SmartphoneModel.objects.all():
        phone.price = 0
        phone.category = default_category
        phone.save()



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(code=set_price_and_category, reverse_code=reverse_set_price_and_category)
    ]
