# Generated by Django 5.0.4 on 2025-10-22 12:44
from datetime import timedelta

from django.db import migrations

from main_app.choices import OrderStatusChoices


def set_delivery_and_warranty(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')
    for o in OrderModel.objects.all():
        if o.status == OrderStatusChoices.PENDING:
            o.delivery = o.order_date + timedelta(days=3)
            o.save()
        elif o.status == OrderStatusChoices.COMPLETED:
            o.warranty = '24 months'
            o.save()
        elif o.status == OrderStatusChoices.CANCELLED:
            o.delete()

def reverse_func(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order_alter_smartphone_price'),
    ]

    operations = [
        migrations.RunPython(code=set_delivery_and_warranty, reverse_code=reverse_func)
    ]

