# Generated by Django 5.0.4 on 2025-11-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_foodcriticrestaurantreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcriticrestaurantreview',
            options={'ordering': ['-rating'], 'verbose_name': 'Food Critic Review', 'verbose_name_plural': 'Food Critic Reviews'},
        ),
        migrations.AlterModelOptions(
            name='menureview',
            options={'ordering': ['-rating'], 'verbose_name': 'Menu Review', 'verbose_name_plural': 'Menu Reviews'},
        ),
    ]
