# Generated by Django 5.0.4 on 2025-10-21 15:40

from django.db import migrations

def create_unique_brands(apps, schema_editor):
    ShoeModel = apps.get_model('main_app', 'Shoe')
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')

    unique_brands = ShoeModel.objects.values_list('brand', flat=True).distinct()

    for b in unique_brands:
        brand = UniqueBrandsModel(brand_name=b)
        brand.save()


def reverse_unique_brands_data_creation(apps, schema_editor):
    UniqueBrandsModel = apps.get_model('main_app', 'UniqueBrands')
    UniqueBrandsModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(code=create_unique_brands, reverse_code=reverse_unique_brands_data_creation)
    ]
