# Generated by Django 5.0.4 on 2025-11-24 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_spacecraft_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecraft',
            name='weight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
